const types = {
  LOAD_STOCK_LIST: 'LOAD_STOCK_LIST',
  LOAD_SECTOR_LIST: 'LOAD_SECTOR_LIST',
  LOAD_INDUSTRY_LIST: 'LOAD_INDUSTRY_LIST',
  LOAD_COUNTRY_LIST: 'LOAD_COUNTRY_LIST',
  SHOW: 'SHOW',
  HIDE: 'HIDE',
  OFFLINE: 'OFFLINE',
  API: 'API',
};

export default types;
